// vue-project/src/components/Header.vue
<template>
  <header>
    <router-link to="/">
      <img :src="require(`../assets/images/home-icon.svg`)" id="home-icon" />
    </router-link>
    <nav>
      <router-link to="/about">About</router-link>
      <router-link to="/create-post"><button>New Post</button></router-link>
    </nav>
  </header>
</template>

<style scoped>
img,
nav {
  display: none;
}

header {
  padding: 2rem;
  margin-top: 3.5rem;
}

h1 {
  text-align: center;
}

a {
  font-size: 2rem;
  color: #1b1c1e;
  text-decoration: none;
}

a:hover {
  color: #4fc08d;
}

@media (min-width: 992px) {
  img,
  nav {
    display: initial;
  }

  header {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  nav {
    display: flex;
    justify-content: space-between;
    align-items: center;
    width: 300px;
  }

  h1 {
    justify-self: center;
  }
}
</style>

<script>
export default {
  name: "Header",
  props: ["currentRoute"]
};
</script>

// svelte-project/src/components/Header.svelte
<script>
  import { Link } from "svelte-routing";
  import { createEventDispatcher } from "svelte";

  const dispatch = createEventDispatcher();
</script>

<style>
  header {
    display: none;
  }

  #home-icon {
    cursor: pointer;
  }

  .links-wrapper {
    display: flex;
    align-items: center;
    justify-content: space-between;

    width: 350px;
  }

  @media (min-width: 992px) {
    header {
      display: flex;
      align-items: center;
      justify-content: space-between;

      padding: 4rem 3rem;
    }
  }
</style>

<header>
  <Link
    to="/"
    on:click={() => dispatch('viewChange', { newPageTitle: 'All posts' })}>
    <img src="/images/home-icon.svg" alt="Home icon" id="home-icon" />
  </Link>
  <div class="links-wrapper">
    <Link
      to="about"
      on:click={() => dispatch('viewChange', { newPageTitle: 'About' })}>
      About
    </Link>
    <Link
      to="create-post"
      on:click={() => dispatch('viewChange', {
          newPageTitle: 'Create a post',
        })}>
      <button>New Post</button>
    </Link>
  </div>
</header>
