// vue-project/src/components/Layout.vue
<template>
  <div>
    <img
      id="menu-icon"
      :src="require(`../assets/images/menu-icon.svg`)"
      @click="showSidedrawer = true"
    />
    <Header />
    <Sidedrawer
      :class="{ show: showSidedrawer }"
      @close-sidedrawer="showSidedrawer = false"
    />
    <h1>{{ currentRouteName }}</h1>
    <slot />
  </div>
</template>

<script>
import Header from "./Header.vue";
import Sidedrawer from "./UI/Sidedrawer.vue";

const routeMappings = {
  "/": "All posts",
  "/about": "About",
};

export default {
  name: "Layout",
  components: {
    Header,
    Sidedrawer,
  },
  data: () => ({
    showSidedrawer: false,
  }),
  computed: {
    currentRouteName() {
      return routeMappings[this.$route.path];
    },
  },
};
</script>

<style scoped>
#menu-icon {
  position: absolute;
  top: 8px;
  left: 8px;
  width: 55px;
}
h1 {
  text-align: center;

  margin-bottom: 3rem;
}
@media (min-width: 992px) {
  #menu-icon {
    display: none;
  }
}
</style>

// svelte-project/src/components/Layout.svelte
<script>
  import Sidedrawer from "./Sidedrawer.svelte";
  import Header from "./Header.svelte";
  import pathnameMapping from "../utils/pathnameMapping";

  //
  export let currentPageName;

  let openSidedrawer = false;

  function closeSidedrawer() {
    openSidedrawer = false;
  }
</script>

<style>
  #sidedrawer-toggler {
    position: absolute;
    top: 10px;
    left: 10px;
    z-index: 2;
  }

  h1 {
    font-size: 4.8rem;
    font-weight: 300;

    text-align: center;

    margin-top: 6rem;
    margin-bottom: 3rem;
  }

  @media (min-width: 992px) {
    #sidedrawer-toggler {
      display: none;
    }

    h1 {
      margin-top: 0;
      margin-bottom: 5rem;
    }
  }
</style>

<img
  on:click={() => (openSidedrawer = true)}
  src="/images/menu-icon.svg"
  alt="Menu icon"
  id="sidedrawer-toggler" />
<Sidedrawer
  on:closeSidedrawer={closeSidedrawer}
  {openSidedrawer}
  on:viewChange />
<Header on:viewChange />
<h1>{currentPageName}</h1>
<slot />
