// svelte-project/src/views/About.svelte
<script>
  import { listen } from "svelte/internal";
</script>

<style>
  main {
    width: 95%;
    max-width: 800px;
    margin-left: auto;
    margin-right: auto;

    text-align: center;
  }

  .dev-opinion {
    margin-bottom: 4rem;
  }

  .dev-opinion h2 {
    font-weight: 700;
    font-size: 2.5rem;

    margin-bottom: 2rem;
  }

  .dev-opinion p {
    margin-bottom: 1.5rem;
  }
</style>

<main>
  <p style="margin-bottom: 5rem;">
    This is a project we made to get familiar with different front end
    frameworks. In this case, we used
    <span>Svelte</span>. Here's what we thought about it:
  </p>
  <article class="dev-opinion">
    <h2>@melosomelo</h2>
    <p>
      I have mixed feelings about
      <span>Svelte</span>. When I first started using it for this project, I
      didn't like it. I think it feels like a simplified version of
      <span class="vue">Vue</span>. I'm not sure if I like or dislike that. I
      preffer the "structure" that comes with
      <span class="vue">Vue</span>. But I totally get why some people might like
      coding with
      <span>Svelte</span>
      due to the simplicity of doing so.
    </p>
    <p>
      One thing that seems really nice about it is that its bundle looks really
      small and efficient, since it's compiled to regular Javascript. That seems
      like a really, realy cool feature.
    </p>
    <p>
      So far,
      <span class="vue">Vue</span>
      &gt=
      <span class="react">React</span>
      &gt
      <span>Svelte</span>.
    </p>
  </article>
  <article class="dev-opinion">
    <h2>@leonandro</h2>
    <p>Yet to give his opinion.</p>
  </article>
</main>

// vue-project/src/views/About.vue
<template>
  <div>
    <p style="margin-bottom: 5rem;">
      This is a project we made to get familiar with different front end frameworks. In this, case,
      we used <span>Vue</span>. Here's what we thought about it:
    </p>

    <div class="developer-opinion">
      <h2>@melosomelo</h2>
      <p>
        I thoguth <span>Vue</span> was pretty simple and really fun to develop with. I started
        learning <span class="react">React</span> this year, so I have some experience with frontend
        frameworks, but <span>Vue</span> is now definetly my second choice! I think it's easier to
        learn that <span class="vue">React</span> and <span>.vue</span> files make things pretty
        sweet. One thing I didn't really like/get used to yet is having to type a lot of things
        within doublequotes. But I guess you can get used to that, just like JSX in
        <span class="react">React</span>.
      </p>
    </div>
    <div class="developer-opinion">
      <h2>@leonandro</h2>
      <p>
        yet to give his opinion.
      </p>
    </div>
  </div>
</template>

<script>
export default {
  name: "About"
};
</script>

<style scoped>
p {
  text-align: center;

  width: 90%;
  max-width: 750px;
  margin-left: auto;
  margin-right: auto;
}
.developer-opinion {
  text-align: center;

  margin-bottom: 3rem;
}
h2 {
  font-size: 2.5rem;
  font-weight: bolder;

  margin-bottom: 2rem;
}
</style>
